version: "3"
services:
  db-backend:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=potentialsi
    ports:
      - "5432:5432"
#  db_mock:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5433:5432"
  frontend:
    image: frontend-localhost:latest
    restart: on-failure
    ports:
      - "4200:4200"
  backend:
    image: backend:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db-backend

#  fluentd:
#      image: fluentd


#    hello-world:
#        image: hello-world
#    volumes:
#      - postgres-db:/var/lib/postgresql/data

#
#  volumes:
#    postgres-db:
#      driver: local
