version: "3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  db_mock:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
#  fluentd:
#      image: fluentd


#    hello-world:
#        image: hello-world
#    volumes:
#      - postgres-db:/var/lib/postgresql/data

#
#  volumes:
#    postgres-db:
#      driver: local
