version: "3"
services:
  db-backend:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=potentialsi
    ports:
      - "5432:5432"
  frontend:
    image: frontend:latest
    restart: on-failure
    ports:
      - "4200:4200"
  ml-module:
    image: ml-module:latest
    restart: on-failure
    ports:
      - "5000:5000"
  backend:
    image: backend:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db-backend

#  fluentd:
#      image: fluentd


#  db_mock:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5433:5432"